### PR TITLE
JCasC compatibility for user property

### PR DESCRIPTION
**Pull request by timja**
See:
https://github.com/jenkinsci/configuration-as-code-plugin/pull/1309

Example yaml:

```yaml
jenkins:
  securityRealm:
    local:
      allowsSignup: true
      enableCaptcha: false
      users:
        - description: "I am admin"
          id: "admin"
          name: "Admin"
          properties:
            - mailer:
                emailAddress: "admin3@example.com"
```

### CODE REVIEW

**Comment by timja** [comment]
Functionality isn’t released in jcasc yet, I added a test for the slack property there as that worked out of the box, I can add a test for mailer there or here or I can leave it if you’re happy that testing the slack property proves the general functionality

**Comment by timja** [comment]
@alecharp there's a test in jcasc here:
https://github.com/jenkinsci/configuration-as-code-plugin/pull/1312

**Comment by alecharp** [comment]
Ok I see why you need those. Even tho I agree with the incremental build, I still feel it should be done in another PR.

**Comment by timja** [comment]
Passing integration test in jcasc:
https://github.com/jenkinsci/configuration-as-code-plugin/pull/1312

**Comment by alecharp** [comment]
Just waiting for the build to finish before merging.

**Comment by alecharp** [comment]
Closing to retrigger the build.

**Comment by timja** [comment]
htmlunit timeouts

**Comment by alecharp** [comment]
Victory!! Thanks @timja

**Comment by timja** [comment]
@alecharp do you plan to release this soon?

**Comment by alecharp** [comment]
I was waiting for master to be built on ci.j.io but forgot. Last build on master failed, pretty sure it's a infra issue. Trying to see if I can retrigger the build, if not, I'll release it today.

**Comment by alecharp** [comment]
The windows branch is not yet built. I'm waiting for this to release it. thank you for reminding me this @timja

**Pull request merged**
