### PR TITLE
Use detached JavaMail plugin

### PR DESCRIPTION
**Pull request by basil**
Downstream of #142 and jenkinsci/jenkins#6165. Bumps the baseline to one containing jenkinsci/jenkins#6165, thus using the detached JavaMail plugin, but does not upgrade to Jakarta Mail.

### CODE REVIEW

**Comment by basil** [comment]
I've marked this as ready for review because the PR is complete, but I'm not in any rush for this to be merged due to the bump in Jenkins baseline. I just wanted to file the PR to close the loop on remaining tasks regarding detaching JavaMail.

**Comment by basil** [comment]
My preference would be to release #168 before releasing this so that the fix from #168 is available to older BOM lines.

**Comment by basil** [comment]
@alecharp Build is green on this as well, though as noted my preference is to release #168 first.

**Comment by alecharp** [comment]
I agree, those changes seems a bit more "dangerous". I'll release the plugin now with this for now.

**Comment by jglick** [comment]
@alecharp if you do not mind, I would like to release this and #144 and move on to an even newer core bump to deal with `instance-identity`.

**Review by jglick — APPROVED** [review]

**Pull request merged**
