### PR TITLE
Mailer: fix missing getter for smtpHost property

### PR DESCRIPTION
**Pull request by metux**
required for configuration-as-code

Signed-off-by: Enrico Weigelt, metux IT consult <info@metux.net>

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
A JIRA issue would help

**Comment by casz** [comment]
Silly there is one, yet linked in the jcasc github issue: https://github.com/jenkinsci/configuration-as-code-plugin/issues/501 
https://issues.jenkins-ci.org/browse/JENKINS-53467
Here ya go 👍

**Comment by oleg-nenashev** [comment]
Thanks. I believe this is a small quick-win patch we should merge. https://github.com/jenkinsci/mailer-plugin/pull/39/ looks like a bigger change from @ndeloof 

@jglick @andresrc  do you maintain the plugin? Or is it a shared ownership across the core team?

**Comment by metux** [comment]
By the way: the Delphi language has an own concept for such things, called 'properties'. Looks like dumb fields to the outside, but one can attach getter/setter code if needed. 

Could we do something similar in Java ?
Problems like this seem to be pretty common (eg. I've just got a report on the same problem w/ the extended mailer plugin).

**Comment by oleg-nenashev** [comment]
It is under discussion for future Java versions. Some languages like C#
support it.

**Comment by metux** [comment]
On 08.09.2018 14:59, Oleg Nenashev wrote:
> It is under discussion for future Java versions. Some languages like C#
> support it.

For our case - when using reflection anyways - there could be a simpler
solution: make those attributes public fields or add some annotation,
so casc+friends could access these fields directly.

Haven't checked whether something calls these getters/setters directly,
or everything (eg. UI, etc) goes via reflection. In that case, we could
get rid of all the trivial getters/setters (only leaving those which
really need something special).


--mtx

-- 
Enrico Weigelt, metux IT consult
Free software and Linux embedded engineering
info@metux.net -- +49-151-27565287

**Comment by ndeloof** [comment]
getter + setter is a very common Java construct, long debated as boilerplate and sometime generated (see [Lombok](https://projectlombok.org))
There's many things to modernize in Jenkins, and getter+setter "issue" is the last one on my list ;)

**Comment by micw** [comment]
Hi. I'm also looking for this fix to use configuration-as-code for automation. Is there anything that prevents this PR to be merged? If not, please do it.
Thank you very much,
Michael.

**Comment by micw** [comment]
So, now we have 3 approvals, a Jira issue and a long discussion. What else is required to have that missing getter added?

Kind regards,
Michael.

**Comment by ndeloof** [comment]
I guess : someone to actively maintain this plugin :)

**Comment by casz** [comment]
well @daniel-beck and @jglick released last and @oleg-nenashev appears to have commit access ;)

**Comment by daniel-beck** [comment]
Both releases were for security fixes, this does not indicate maintainership.

**Comment by micw** [comment]
@daniel-beck Does this mean, that the plug-in is not maintained?
Could you have a look into that minimal PR and maybe merge/release it? It just adds one missing getter, so that plug-in setup can be automated using the configuration-as-code plug-in. It's reviewed and approved by 3 members.
Thank you very much,
Michael.

**Comment by oleg-nenashev** [comment]
@jglick I believe you are formally the maintainer then. Would you be fine if I also formally join the maintenance team so that I deliver the stuff?

**Comment by jglick** [comment]
I am not a maintainer. If you would like to take over, go ahead.

**Comment by ndeloof** [comment]
@olivergondza seems you're maintainer on mailer plugin, can you please check this ?

**Comment by oleg-nenashev** [comment]
Let's just call Jenkins core team as maintainers. Will do the job

**Comment by oleg-nenashev** [comment]
https://github.com/jenkins-infra/repository-permissions-updater/pull/892

**Comment by micw** [comment]
@oleg-nenashev Thank you very much!

**Comment by micw** [comment]
@oleg-nenashev Thank you very much!

**Pull request merged**
