### PR TITLE
Mailer should use its own i18n messages instead of old Jenkins dependency

### PR DESCRIPTION
**Pull request by i386**
Pretty straightforward - when mailer was split from core its message bundle source was copied into the plugin but was never forced to generate its own `Messages` class. This change introduces the ability to generate its own `Messages` and updates the code to reference it.

@jenkinsci/code-reviewers

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@i386 AFAIK any plugin in Jenkins is able to generate Messages, because Maven Localizer is defined in the Parent POM. So I'm not exactly sure why there was a need to tweak pom.xml and to rename Message files here

**Comment by slide** [comment]
I actually didn't merge this, one of my kids must have. I'll lock my computer while stepping away. This should be reveerted.

**Comment by slide** [comment]
Reverted

**Comment by oleg-nenashev** [comment]
Uhh, my cat has merged the PR once :)

**Comment by slide** [comment]
The merge button is a nice green color, attracts animals and children :-)

**Pull request merged**
