### PR TITLE
New extension point in mailer-plugin exclude email recipients

### PR DESCRIPTION
**Pull request by mudiobada**
This change simply adds an extension point to mailer-plugin that filters email recipients.

By default nothing is filtered. Also the mailer-plugin functionality is not extended to support any filtering.

This change allows writing simple plugins that make it possible to exclude certain email addresses
from emails sent by a Jenkins instance (e.g. system users or commiters to upstream projects)

Currently, implementing such a feature could be done using the mail-ext scripts. 
However, using mail-ext requires changes to job configurations and writing scripts
where a custom plugin that implements an ExtensionPoint would be more appropriate.

If this change makes it into mailer-plugin/master, a new plugin can be created that show cases
this feature (e.g. as implemented by mail-exts "excludedRecipients").

### CODE REVIEW

**Comment by MichaelSp** [comment]
How do I use/configure this feature?

**Comment by mudiobada** [comment]
Are you looking at building a plugin or would you like to filter out some recipients with the mailer plugin?

This pull request is for the former. I am not aware of a public plugin that does the later but could provide an example.

**Comment by MichaelSp** [comment]
Yes, I'm looking for the later. 
Would be really nice to expose this functionality via config.xml or gui within this plugin. 
Do you think this is possible?

**Comment by mudiobada** [comment]
@MichaelSp I created a simple example at pushed to https://github.com/mudiobada/mail-filter-plugin

**Comment by MichaelSp** [comment]
Exactly what I wanted. Thanks

**Pull request merged**
