### PR TITLE
[JENKINS-33291] Additional Tests

### PR DESCRIPTION
**Pull request by andresrc**
See [JENKINS-33291](https://issues.jenkins-ci.org/browse/JENKINS-33291):

Test post build step options:
* Notify in every unstable build.
* Notify "culprits".

Includes some refactoring of the existing tests.

Edited after merging master: was downstream of https://github.com/jenkinsci/mailer-plugin/pull/24 (will rebase once upstream is merged, at this point only https://github.com/jenkinsci/mailer-plugin/commit/73c521ca2f40b0d9d7bf786a39bf4d5dddec915c is significant).

@reviewbybees

### CODE REVIEW

**Comment by armfergom** [comment]
Some things have been removed from the pom (dependencies, plugins, properties..). I am assuming they are all in the new parent pom instead, correct?

If so, this is a :bee: for me

**Comment by jglick** [comment]
> will rebase once upstream is merged

Suffices to `git merge master`, since those commits are now in `master`. GitHub will do the right thing.

**Comment by jglick** [comment]
:bee:

**Comment by amuniz** [comment]
:bee:

**Comment by armfergom** [comment]
:bee:

**Comment by andresrc** [comment]
@reviewbybees done

**Comment by andresrc** [comment]
@rsandell do you want to have a look or can I merge?

**Comment by abayer** [comment]
Merging!

**Pull request merged**
