### PR TITLE
Hacktoberfest: Trim white space

### PR DESCRIPTION
**Pull request by darinpope**
Adding trimming to the following attributes:

* SMTP server (smtpHost)
* User Name (authentication/user)
* SMTP Port (smtpHost)
* Reply-To Address (replyToAddress)
* Charset (charset)

Also standardized the reference to Util.fixEmptyAndTrim

Signed-off-by: Darin Pope <darin@planetpope.com>

### CODE REVIEW

**Comment by darinpope** [comment]
This PR attempts to fix the fields that have space padded inputs in the image:

Screen Shot 2020-10-13 at 5 29 16 PM

**Comment by darinpope** [comment]
Can someone force another build? Looks like "java.net.SocketTimeoutException: Read timed out" popped up on the linux-8 agent.

**Review by oleg-nenashev — APPROVED** [review]
looks good, thanks!

**Review by alecharp — APPROVED** [review]

**Comment by alecharp** [comment]
Thank you for your contribution.

**Comment by ottlinger** [comment]
@oleg-nenashev Could this PR be merged as it greatly simplifies usage of this plugin ? Thanks

**Pull request merged**
